### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Route' not found in ...

### ISSUE THREAD

**Issue by unclesamwk** [juanal98/Laravel-Proxy-Helper#1]
Hey,

i would use the example.php but i get following error ...

```

Fatal error: Uncaught Error: Class 'Route' not found in /html/path/index.php:17 Stack trace: #0 {main} thrown in /html/path/index.php on line 17

```
PHP7.3

Anyone an idea?

greetings
Sam

**Comment by jespanag** [comment]
Are u using laravel?

This extension is designed for laravel,

u can read about Routes in laravel here:
https://laravel.com/docs/8.x/routing

If u are not using laravel i recommend it, or u must adapt code for PHP without framework.
